version: "3.7"
services:
  frontend:
    build: ./frontend
    ports:
     - "8081:80"
    depends_on:
      - bff
      - api
  bff:
    build: ./backend-for-frontend
    command: npm run dev
    ports:
     - "8080:80"
  api:
    build: ./api
    command: sh -c '/var/service/wait-for.sh db:5432 -- npm run dev'
    ports:
      - "8082:80"
    depends_on:
      - db
      - queue
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: cards
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./db-data:/var/lib/postgresql/data
  queue:
    image: softwaremill/elasticmq:0.14.12
volumes:
  db-data:
