version: "3.7"
services:
  service:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8082:8082
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    command: sh -c '/var/service/wait-for.sh db:5432 -- npm run watch'
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: cards
    volumes:
      - ./db-data:/var/lib/postgresql/data
volumes:
  db-data:
